title: BeoLiving Intelligence
author: Khimo
email: support@khimo.com
description: > # this means to ignore newlines until "twitter_username:"
  In this site will will keep updated documentation on how to use the BeoLiving
  Intelligence controller and the BeoLiving App. [](https://ik-avi.github.io/doctest/)
# social links
twitter_username: khimo_remoto
github_username:  khimo
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - readme.md
 - bli-guides/main.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
